name: Run tests

on: pull_request_target

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      # straight from neovim-CI,
      # https://github.com/neovim/neovim/blob/3a5dddf24f9d4d8959194b0cd3c6a7dd0cbd73ae/.github/workflows/ci.yml#L127
      # asdf adsf
      - run: |
          sudo add-apt-repository ppa:neovim-ppa/stable
          sudo apt-get update
          sudo apt-get remove libuv1
          sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          cpanminus \
          curl \
          gettext \
          libtool-bin \
          locales-all \
          ninja-build \
          pkg-config \
          unzip
          sudo apt-get remove libuv1-dev

      - run: make test
