name: Run tests

on: pull_request_target

jobs:
  tests:
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - run: make test
